title: "Sculpto Guide"
description: "Tips, tricks, and guides for getting the most out of your Sculpto 3D printer - including G-code control, Cura settings, maintenance, and more."
theme: minima
# highlighter: rouge
# kramdown:
# math_engine: mathjax
# syntax_highlighter: rouge
